export const Utils = {
  NAV_LINKS: [
    { id: 1, display: "Home", href: "/" },
    { id: 2, display: "All Games", href: "/all-games" },
    { id: 3, display: "All Categories", href: "/all-categories" },
    { id: 4, display: "Login", href: "/login" },
    { id: 5, display: "Register", href: "/register" },
  ],
  ALL_CATEGORIES: [
    { id: 1, display: "MMO", href: "/games/mmo" },
    { id: 2, display: "MMORPG", href: "/games/mmorpg" },
    { id: 3, display: "Shooter", href: "/games/shooter" },
    { id: 4, display: "Strategy", href: "/games/strategy" },
    { id: 5, display: "Moba", href: "/games/moba" },
    { id: 6, display: "Card Games", href: "/games/card" },
    { id: 7, display: "Racing", href: "/games/racing" },
    { id: 8, display: "Sports", href: "/games/sports" },
    { id: 9, display: "Social", href: "/games/social" },
    { id: 10, display: "Fighting", href: "/games/fighting" },
    { id: 11, display: "MMOFPS", href: "/games/mmofps" },
    { id: 12, display: "Action RPG", href: "/games/action-rpg" },
    { id: 13, display: "Sandbox", href: "/games/sandbox" },
    { id: 14, display: "Open World", href: "/games/open-world" },
    { id: 15, display: "Survival", href: "/games/survival" },
    { id: 16, display: "Battle Royale", href: "/games/battle-royale" },
    { id: 17, display: "MMOTPS", href: "/games/mmotps" },
    { id: 18, display: "Anime", href: "/games/anime" },
    { id: 19, display: "PvP", href: "/games/pvp" },
    { id: 20, display: "PvE", href: "/games/pve" },
    { id: 21, display: "Pixel", href: "/games/pixel" },
    { id: 22, display: "MMORTS", href: "/games/mmorts" },
    { id: 23, display: "Fantasy", href: "/games/fantasy" },
    { id: 24, display: "Sci-Fi", href: "/games/sci-fi" },
    { id: 25, display: "Action", href: "/games/action" },
    { id: 26, display: "Voxel", href: "/games/voxel" },
    { id: 27, display: "Zombie", href: "/games/zombie" },
    { id: 28, display: "Turn-Based", href: "/games/turn-based" },
    { id: 29, display: "First Person View", href: "/games/first-person" },
    { id: 30, display: "Third Person View", href: "/games/third-Person" },
    { id: 31, display: "Top-Down View", href: "/games/top-down" },
    { id: 32, display: "3D Graphics", href: "/games/3d" },
    { id: 33, display: "2D Graphics", href: "/games/2d" },
    { id: 34, display: "Tank", href: "/games/tank" },
    { id: 35, display: "Space", href: "/games/space" },
    { id: 36, display: "Sailing", href: "/games/sailing" },
    { id: 37, display: "Side Scroller", href: "/games/side-scroller" },
    { id: 38, display: "Superhero", href: "/games/superhero" },
    { id: 39, display: "Permadeath", href: "/games/permadeath" },
  ],
};
