export const Utils = {
  NAV_LINKS: [
    { id: 1, display: "Home", href: "/", hidden: false },
    { id: 2, display: "Games", href: "/games", hidden: false },
    { id: 3, display: "Categories", href: "/categories", hidden: false },
    { id: 4, display: "Login", href: "/login", hidden: true },
    { id: 5, display: "Register", href: "/register", hidden: true },
  ],
  ALL_CATEGORIES: [
    { id: 1, display: "MMO", href: "/categories/mmo" },
    { id: 2, display: "MMORPG", href: "/categories/mmorpg" },
    { id: 3, display: "Shooter", href: "/categories/shooter" },
    { id: 4, display: "Strategy", href: "/categories/strategy" },
    { id: 5, display: "Moba", href: "/categories/moba" },
    { id: 6, display: "Card Games", href: "/categories/card" },
    { id: 7, display: "Racing", href: "/categories/racing" },
    { id: 8, display: "Sports", href: "/categories/sports" },
    { id: 9, display: "Social", href: "/categories/social" },
    { id: 10, display: "Fighting", href: "/categories/fighting" },
    { id: 11, display: "MMOFPS", href: "/categories/mmofps" },
    { id: 12, display: "Action RPG", href: "/categories/action-rpg" },
    { id: 13, display: "Sandbox", href: "/categories/sandbox" },
    { id: 14, display: "Open World", href: "/categories/open-world" },
    { id: 15, display: "Survival", href: "/categories/survival" },
    { id: 16, display: "Battle Royale", href: "/categories/battle-royale" },
    { id: 17, display: "MMOTPS", href: "/categories/mmotps" },
    { id: 18, display: "Anime", href: "/categories/anime" },
    { id: 19, display: "PvP", href: "/categories/pvp" },
    { id: 20, display: "PvE", href: "/categories/pve" },
    { id: 21, display: "Pixel", href: "/categories/pixel" },
    { id: 22, display: "MMORTS", href: "/categories/mmorts" },
    { id: 23, display: "Fantasy", href: "/categories/fantasy" },
    { id: 24, display: "Sci-Fi", href: "/categories/sci-fi" },
    { id: 25, display: "Action", href: "/categories/action" },
    { id: 26, display: "Voxel", href: "/categories/voxel" },
    { id: 27, display: "Zombie", href: "/categories/zombie" },
    { id: 28, display: "Turn-Based", href: "/categories/turn-based" },
    { id: 29, display: "First Person View", href: "/categories/first-person" },
    { id: 30, display: "Third Person View", href: "/categories/third-Person" },
    { id: 31, display: "Top-Down View", href: "/categories/top-down" },
    { id: 32, display: "3D Graphics", href: "/categories/3d" },
    { id: 33, display: "2D Graphics", href: "/categories/2d" },
    { id: 34, display: "Tank", href: "/categories/tank" },
    { id: 35, display: "Space", href: "/categories/space" },
    { id: 36, display: "Sailing", href: "/categories/sailing" },
    { id: 37, display: "Side Scroller", href: "/categories/side-scroller" },
    { id: 38, display: "Superhero", href: "/categories/superhero" },
    { id: 39, display: "Permadeath", href: "/categories/permadeath" },
  ],
};
